### ISSUE TITLE
Missing launch file: fast_with_vi_sensor.launch

### ISSUE THREAD

**Issue by t-thanh** [ZJU-FAST-Lab/forces_resilient_planner#1]
I found 2 issues when trying to follow your instruction to reproduce the result with simulator:
- I can't find the `fast_with_vi_sensor.launch` even in the `https://github.com/yuwei-wu/rotors_simulator`
- The launch file `rotor_sim.launch` is in the `plan_manage` package - not in the `resilient_planner` stack. 

There is some issues with the installations also, but I manage (not sure if it is correct because I can't test without the `fast_with_vi_sensor.launch` file. Let's see. 

Keep up the great work. Thanks,

**Comment by yuwei-wu** [comment]
1. there is some inconsistency about these two repos, I've renamed the file fast_quad.launch as fast_with_vi_sensor.launch
2. it's ok because the package name is resilient_planner, you can check the CMake list file.
3. The installations about dependencies are a little complicated. For rotorS, It's better to follow the full guidance of rotorS but replace it with my revised version. If you found any trouble with it, feel free to contact me. I will also test the revised version of rotorS. Thanks.

**Comment by t-thanh** [comment]
1. Solved. Confirmed. Thanks
2. The launch file has the wrong file name should be `rotors_sim.launch` instead of `rotor_sim.launch` - I create a pull request for it.
